2014-01-08 13:54:11+0800 [scrapy] INFO: Scrapy 0.20.2 started (bot: PolySpider)
2014-01-08 13:54:11+0800 [scrapy] DEBUG: Optional features available: ssl, http11, boto, django
2014-01-08 13:54:11+0800 [scrapy] DEBUG: Overridden settings: {'NEWSPIDER_MODULE': 'PolySpider.spiders', 'SPIDER_MODULES': ['PolySpider.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.54 Safari/536.5', 'DOWNLOAD_DELAY': 2, 'BOT_NAME': 'PolySpider'}
2014-01-08 13:54:11+0800 [scrapy] DEBUG: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2014-01-08 13:54:11+0800 [scrapy] DEBUG: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2014-01-08 13:54:11+0800 [scrapy] DEBUG: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2014-01-08 13:54:11+0800 [scrapy] DEBUG: Enabled item pipelines: PolySpiderPipeline, CategorizingPipeline, CheckAppPipeline, CheckAppDetailsPipeline, UpdateCategoryPipeline, StatusRecordPipeline
2014-01-08 13:54:11+0800 [appstar] INFO: Spider opened
2014-01-08 13:54:11+0800 [appstar] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2014-01-08 13:54:11+0800 [scrapy] DEBUG: Telnet console listening on 0.0.0.0:6023
2014-01-08 13:54:11+0800 [scrapy] DEBUG: Web service listening on 0.0.0.0:6080
2014-01-08 13:54:17+0800 [appstar] DEBUG: Crawled (200) <GET http://appstar.com.cn/> (referer: None)
2014-01-08 13:54:17+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/107.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:17+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/107.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:20+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/106.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:20+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/106.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:22+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/105.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:22+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/105.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:24+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/104.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:24+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/104.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:26+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/103.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:26+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/103.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:28+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/102.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:28+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/102.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:31+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/101.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:31+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/101.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:34+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/100.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:34+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/100.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:36+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/99.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:36+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/99.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:39+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/98.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:39+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/98.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:42+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/97.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:42+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/97.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:44+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/96.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:44+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/96.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:46+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/95.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:46+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/95.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:48+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/94.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:48+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/94.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:50+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/93.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:50+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/93.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:51+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/92.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:51+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/92.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 45, in parse_app
	    item['author'] = sel.xpath('//*[@id="appDetail"]/li[2]/text()').extract()[2][3:]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:53+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/3192.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:53+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/3192.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:55+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/23152.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:55+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/23152.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:54:57+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30029.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:54:57+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30029.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:00+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30028.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:00+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30028.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:02+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30027.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:02+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30027.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:05+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30026.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:05+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30026.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:07+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30025.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:07+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30025.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:09+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30024.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:09+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30024.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:11+0800 [appstar] INFO: Crawled 25 pages (at 25 pages/min), scraped 0 items (at 0 items/min)
2014-01-08 13:55:11+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30023.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:11+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30023.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:13+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30022.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:13+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30022.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:14+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30021.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:15+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30021.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:17+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30020.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:17+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30020.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:20+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30019.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:20+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30019.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:23+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30018.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:23+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30018.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:25+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30017.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:25+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30017.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:28+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30016.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:28+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30016.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:31+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30015.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:31+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30015.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:34+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30014.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:34+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30014.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:37+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30013.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:37+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30013.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:40+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30012.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:40+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30012.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:42+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30011.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:42+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30011.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:45+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30010.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:45+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30010.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:48+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30009.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:48+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30009.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:49+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30008.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:49+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30008.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:51+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30007.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:51+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30007.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:54+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30006.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:54+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30006.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:56+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30005.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:56+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30005.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:55:58+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30004.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:55:58+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30004.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:01+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30003.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:01+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30003.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:03+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30002.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:03+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30002.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:05+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30001.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:05+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30001.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:07+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/30000.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:07+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/30000.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:10+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29999.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:10+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29999.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:11+0800 [appstar] INFO: Crawled 50 pages (at 25 pages/min), scraped 0 items (at 0 items/min)
2014-01-08 13:56:12+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29998.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:12+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29998.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:15+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29997.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:15+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29997.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:18+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29996.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:18+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29996.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:20+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29995.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:20+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29995.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:23+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29994.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:23+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29994.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:25+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29993.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:25+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29993.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:27+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29992.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:27+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29992.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:30+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29991.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:30+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29991.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:33+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29990.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:33+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29990.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:35+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29989.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:35+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29989.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:38+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29988.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:38+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29988.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:41+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29987.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:41+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29987.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:44+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29986.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:44+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29986.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:46+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29985.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:46+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29985.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:47+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29984.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:47+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29984.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:50+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29983.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:50+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29983.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:53+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29982.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:53+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29982.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:55+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29981.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:55+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29981.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:57+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29980.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:57+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29980.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:56:59+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29979.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:56:59+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29979.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:01+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29978.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:01+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29978.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:03+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29977.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:03+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29977.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:06+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29976.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:06+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29976.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:09+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29975.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:09+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29975.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:11+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29974.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:11+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29974.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:11+0800 [appstar] INFO: Crawled 75 pages (at 25 pages/min), scraped 0 items (at 0 items/min)
2014-01-08 13:57:13+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29973.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:13+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29973.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:15+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29972.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:15+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29972.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:17+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29971.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:17+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29971.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:20+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29970.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:20+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29970.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:22+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29969.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:22+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29969.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:25+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29968.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:25+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29968.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:27+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29967.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:27+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29967.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:30+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29966.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:30+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29966.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:33+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29965.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:33+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29965.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:35+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29964.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:35+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29964.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:38+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29963.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:38+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29963.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:41+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29962.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:41+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29962.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:44+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29961.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:44+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29961.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:47+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29960.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:47+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29960.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:49+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29959.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:49+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29959.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:51+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29958.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:51+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29958.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:53+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29957.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:53+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29957.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:54+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29956.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:54+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29956.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:57:57+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29955.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:57:57+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29955.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:00+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29954.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:00+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29954.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:02+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29953.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:02+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29953.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:03+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29952.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:03+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29952.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:06+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29951.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:06+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29951.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:08+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29950.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:08+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29950.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:09+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29949.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:09+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29949.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:11+0800 [appstar] INFO: Crawled 100 pages (at 25 pages/min), scraped 0 items (at 0 items/min)
2014-01-08 13:58:12+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29948.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:12+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29948.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:14+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29947.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:14+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29947.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:17+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29946.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:17+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29946.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:20+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29945.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:20+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29945.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:21+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29944.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:21+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29944.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:23+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29943.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:23+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29943.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:26+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29942.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:26+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29942.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:28+0800 [scrapy] INFO: Received SIGTERM, shutting down gracefully. Send again to force 
2014-01-08 13:58:28+0800 [appstar] INFO: Closing spider (shutdown)
2014-01-08 13:58:29+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29941.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:29+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29941.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:31+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29940.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:31+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29940.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:34+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29939.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:34+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29939.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
2014-01-08 13:58:37+0800 [appstar] DEBUG: Crawled (200) <GET http://www.appstar.com.cn/ace/store/29938.htm> (referer: http://appstar.com.cn/)
2014-01-08 13:58:37+0800 [appstar] ERROR: Spider error processing <GET http://www.appstar.com.cn/ace/store/29938.htm>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/eric/project/PolySpider/src/PolySpider/spiders/appstar_spider.py", line 36, in parse_app
	    item['apk_url'] = "http://www.appstar.com.cn" + sel.xpath("//*[@id='appDetail']/li[1]/a/@href").extract()[0]
	exceptions.IndexError: list index out of range
	
